# Generated by Django 5.1.2 on 2024-10-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=200)),
                ('Sucursal', models.CharField(max_length=200)),
                ('Aspirante', models.CharField(max_length=200)),
            ],
        ),
    ]
